//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecreationalRespiteDashboardDesigned.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class events
    {
        public int Id { get; set; }
        public string cost { get; set; }
        public string date { get; set; }
        public string endTime { get; set; }
        public string eventDescription { get; set; }
        public string eventImage { get; set; }
        public string eventName { get; set; }
        public string location { get; set; }
        public string region { get; set; }
        public string startTime { get; set; }
        public string totalSeats { get; set; }
    }
}
