//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecreationalRespiteDashboardDesigned.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecDatabaseModelContainer : DbContext
    {
        public RecDatabaseModelContainer()
            : base("name=RecDatabaseModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserInformation> UserInformations { get; set; }
        public virtual DbSet<participants> participants { get; set; }
        public virtual DbSet<articles> articles { get; set; }
        public virtual DbSet<diagnosis> diagnosis { get; set; }
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<registration> registrations { get; set; }
        public virtual DbSet<regions> regions { get; set; }
    }
}
