//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecreationalRespiteDashboardDesigned.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public int id { get; set; }
        public int eventID { get; set; }
        public string username { get; set; }
        public string age { get; set; }
        public string allergies { get; set; }
        public string email { get; set; }
        public string emergencyPhone { get; set; }
        public string expectationsAndGoals { get; set; }
        public string location { get; set; }
        public string name { get; set; }
        public string paymentType { get; set; }
        public string phone { get; set; }
        public string programOfInterest { get; set; }
        public string recreationalInterest { get; set; }
        public string specialNeeds { get; set; }
    }
}
